### ISSUE TITLE
M2DP问题

### ISSUE THREAD

**Issue by SlamCabbage** [gloryhry/M2DP-CPP#1]
请问下，M2DP的描述子之间是用什么方法来匹配的呢？是和Scan Context一样用的cosine 距离吗？

**Comment by gloryhry** [comment]
我看论文里好像也没有详细说明，我就直接用欧式距离算的，不过当时是用在毫米波的点云上的，效果不怎么样，后面也没深入研究了。

**Comment by SlamCabbage** [comment]
感谢。我当时也尝试了几种相似度计算方法，可能是这个方法相对较老，对一些新传感器数据（例如车载lidar）不再适用。
